name: a_check_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
#  google_fonts: ^6.1.0
  side_navigation: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Black.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 800
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 900
        - asset: fonts/Inter-Thin.ttf
          weight: 300
        - asset: fonts/Inter-Light.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 100
