name: a_check_web
description: An attendance management system for checking attendance.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  cloud_firestore_odm: ^1.0.0-dev.76
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
#  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  side_navigation: ^1.0.4
  firebase_auth: ^4.15.0
  firebase_ui_auth: ^1.10.0
  data_table_2: ^2.5.9
  firebase_storage: ^11.5.3
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  universal_html: ^2.2.4
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  csv: ^5.1.1
  path_provider: ^2.1.1
  file_saver: ^0.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.76
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Black.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 800
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 900
        - asset: fonts/Inter-Thin.ttf
          weight: 300
        - asset: fonts/Inter-Light.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 100
